trigger:
  branches:
    include:
    - master
pool:
  name: demopipeline
stages:
- stage: __default
  jobs:
  - deployment: VMDeploy
    displayName: Deploy to VM
    environment:
      name: env-demopipeline
      resourceName: dsv-linux-01
      resourceType: virtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadGitHubRelease@0
            displayName: 'Download Release'
            inputs:
              connection: 'unioliveira'
              userRepository: 'unioliveira/python-docs-hello-world-2'
              defaultVersionType: 'latest'
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.x'
            displayName: 'Use Python 3.x'
          - task: CmdLine@2
            displayName: 'Install dependencies'
            inputs:
              script: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt


          - task: CmdLine@2
            displayName: 'Update execution log'
            inputs:
              script: "echo \"`date` - OK - Execucao com sucesso\" >> /tmp/result.log"

